# Generated by Django 3.2 on 2021-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
